#!/usr/bin/env bash
# displays Best School 10 times, with while

i=0
while [ $i -le 10 ]
do
    if [ $i = 9 ]
    then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    (( i++ ))
done
