#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo $minutes
        (( minutes++ ))
    done
    (( hour++ ))
done
